server:
  port: 8080

spring:
  application:
    name: ezdo

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ezdo}
    username: ${SPRING_DATASOURCE_USERNAME:ezdo}
    password: ${SPRING_DATASOURCE_PASSWORD:ezdo}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
