package com.ezdo.service;

import com.ezdo.entity.Item;
import com.ezdo.entity.ItemType;
import com.ezdo.entity.Rarity;
import com.ezdo.repository.ItemRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Service;

import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class ItemSeedService implements CommandLineRunner {

    private final ItemRepository itemRepository;

    @Override
    public void run(String... args) throws Exception {
        if (itemRepository.count() == 0) {
            log.info("Store is empty. Seeding default gamification items...");

            List<Item> defaultItems = List.of(
                    // Frames (Served from Spring Boot static resources)
                    Item.builder()
                            .name("Celestial Orbit 1")
                            .description("A beautiful Celestial Orbit 1 frame.")
                            .price(150)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/celestial_orbit_01.png")
                            .info("celestial_orbit_01")
                            .build(),
                    Item.builder()
                            .name("Celestial Orbit 2")
                            .description("A beautiful Celestial Orbit 2 frame.")
                            .price(400)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/celestial_orbit_02.png")
                            .info("celestial_orbit_02")
                            .build(),
                    Item.builder()
                            .name("Celestial Orbit 3")
                            .description("A beautiful Celestial Orbit 3 frame.")
                            .price(900)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/celestial_orbit_03.png")
                            .info("celestial_orbit_03")
                            .build(),
                    Item.builder()
                            .name("Celestial Orbit 4")
                            .description("A beautiful Celestial Orbit 4 frame.")
                            .price(2000)
                            .rarity(Rarity.EPIC)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/celestial_orbit_04.png")
                            .info("celestial_orbit_04")
                            .build(),
                    Item.builder()
                            .name("Celestial Orbit 5")
                            .description("A beautiful Celestial Orbit 5 frame.")
                            .price(5000)
                            .rarity(Rarity.LEGENDARY)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/celestial_orbit_05.png")
                            .info("celestial_orbit_05")
                            .build(),
                    Item.builder()
                            .name("Cloud Stratus Dark 1")
                            .description("A beautiful Cloud Stratus Dark 1 frame.")
                            .price(50)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/cloud_stratus_dark_01.png")
                            .info("cloud_stratus_dark_01")
                            .build(),
                    Item.builder()
                            .name("Cloud Stratus Dark 2")
                            .description("A beautiful Cloud Stratus Dark 2 frame.")
                            .price(200)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/cloud_stratus_dark_02.png")
                            .info("cloud_stratus_dark_02")
                            .build(),
                    Item.builder()
                            .name("Cloud Stratus Dark 3")
                            .description("A beautiful Cloud Stratus Dark 3 frame.")
                            .price(500)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/cloud_stratus_dark_03.png")
                            .info("cloud_stratus_dark_03")
                            .build(),
                    Item.builder()
                            .name("Cloud Stratus Dark 4")
                            .description("A beautiful Cloud Stratus Dark 4 frame.")
                            .price(1200)
                            .rarity(Rarity.EPIC)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/cloud_stratus_dark_04.png")
                            .info("cloud_stratus_dark_04")
                            .build(),
                    Item.builder()
                            .name("Cloud Stratus Dark 5")
                            .description("A beautiful Cloud Stratus Dark 5 frame.")
                            .price(3000)
                            .rarity(Rarity.LEGENDARY)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/cloud_stratus_dark_05.png")
                            .info("cloud_stratus_dark_05")
                            .build(),
                    Item.builder()
                            .name("Cloud Stratus Light 1")
                            .description("A beautiful Cloud Stratus Light 1 frame.")
                            .price(50)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/cloud_stratus_light_01.png")
                            .info("cloud_stratus_light_01")
                            .build(),
                    Item.builder()
                            .name("Cloud Stratus Light 2")
                            .description("A beautiful Cloud Stratus Light 2 frame.")
                            .price(200)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/cloud_stratus_light_02.png")
                            .info("cloud_stratus_light_02")
                            .build(),
                    Item.builder()
                            .name("Cloud Stratus Light 3")
                            .description("A beautiful Cloud Stratus Light 3 frame.")
                            .price(500)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/cloud_stratus_light_03.png")
                            .info("cloud_stratus_light_03")
                            .build(),
                    Item.builder()
                            .name("Cloud Stratus Light 4")
                            .description("A beautiful Cloud Stratus Light 4 frame.")
                            .price(1200)
                            .rarity(Rarity.EPIC)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/cloud_stratus_light_04.png")
                            .info("cloud_stratus_light_04")
                            .build(),
                    Item.builder()
                            .name("Cloud Stratus Light 5")
                            .description("A beautiful Cloud Stratus Light 5 frame.")
                            .price(3000)
                            .rarity(Rarity.LEGENDARY)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/cloud_stratus_light_05.png")
                            .info("cloud_stratus_light_05")
                            .build(),
                    Item.builder()
                            .name("Floating Isles Dark 1")
                            .description("A beautiful Floating Isles Dark 1 frame.")
                            .price(110)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/floating_isles_dark_01.png")
                            .info("floating_isles_dark_01")
                            .build(),
                    Item.builder()
                            .name("Floating Isles Dark 2")
                            .description("A beautiful Floating Isles Dark 2 frame.")
                            .price(320)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/floating_isles_dark_02.png")
                            .info("floating_isles_dark_02")
                            .build(),
                    Item.builder()
                            .name("Floating Isles Dark 3")
                            .description("A beautiful Floating Isles Dark 3 frame.")
                            .price(740)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/floating_isles_dark_03.png")
                            .info("floating_isles_dark_03")
                            .build(),
                    Item.builder()
                            .name("Floating Isles Dark 4")
                            .description("A beautiful Floating Isles Dark 4 frame.")
                            .price(1680)
                            .rarity(Rarity.EPIC)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/floating_isles_dark_04.png")
                            .info("floating_isles_dark_04")
                            .build(),
                    Item.builder()
                            .name("Floating Isles Dark 5")
                            .description("A beautiful Floating Isles Dark 5 frame.")
                            .price(4200)
                            .rarity(Rarity.LEGENDARY)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/floating_isles_dark_05.png")
                            .info("floating_isles_dark_05")
                            .build(),
                    Item.builder()
                            .name("Floating Isles Light 1")
                            .description("A beautiful Floating Isles Light 1 frame.")
                            .price(110)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/floating_isles_light_01.png")
                            .info("floating_isles_light_01")
                            .build(),
                    Item.builder()
                            .name("Floating Isles Light 2")
                            .description("A beautiful Floating Isles Light 2 frame.")
                            .price(320)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/floating_isles_light_02.png")
                            .info("floating_isles_light_02")
                            .build(),
                    Item.builder()
                            .name("Floating Isles Light 3")
                            .description("A beautiful Floating Isles Light 3 frame.")
                            .price(740)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/floating_isles_light_03.png")
                            .info("floating_isles_light_03")
                            .build(),
                    Item.builder()
                            .name("Floating Isles Light 4")
                            .description("A beautiful Floating Isles Light 4 frame.")
                            .price(1680)
                            .rarity(Rarity.EPIC)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/floating_isles_light_04.png")
                            .info("floating_isles_light_04")
                            .build(),
                    Item.builder()
                            .name("Floating Isles Light 5")
                            .description("A beautiful Floating Isles Light 5 frame.")
                            .price(4200)
                            .rarity(Rarity.LEGENDARY)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/floating_isles_light_05.png")
                            .info("floating_isles_light_05")
                            .build(),
                    Item.builder()
                            .name("Golden Sunrise Dark 1")
                            .description("A beautiful Golden Sunrise Dark 1 frame.")
                            .price(90)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/golden_sunrise_dark_01.png")
                            .info("golden_sunrise_dark_01")
                            .build(),
                    Item.builder()
                            .name("Golden Sunrise Dark 2")
                            .description("A beautiful Golden Sunrise Dark 2 frame.")
                            .price(280)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/golden_sunrise_dark_02.png")
                            .info("golden_sunrise_dark_02")
                            .build(),
                    Item.builder()
                            .name("Golden Sunrise Dark 3")
                            .description("A beautiful Golden Sunrise Dark 3 frame.")
                            .price(660)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/golden_sunrise_dark_03.png")
                            .info("golden_sunrise_dark_03")
                            .build(),
                    Item.builder()
                            .name("Golden Sunrise Dark 4")
                            .description("A beautiful Golden Sunrise Dark 4 frame.")
                            .price(1520)
                            .rarity(Rarity.EPIC)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/golden_sunrise_dark_04.png")
                            .info("golden_sunrise_dark_04")
                            .build(),
                    Item.builder()
                            .name("Golden Sunrise Dark 5")
                            .description("A beautiful Golden Sunrise Dark 5 frame.")
                            .price(3800)
                            .rarity(Rarity.LEGENDARY)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/golden_sunrise_dark_05.png")
                            .info("golden_sunrise_dark_05")
                            .build(),
                    Item.builder()
                            .name("Golden Sunrise Light 1")
                            .description("A beautiful Golden Sunrise Light 1 frame.")
                            .price(90)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/golden_sunrise_light_01.png")
                            .info("golden_sunrise_light_01")
                            .build(),
                    Item.builder()
                            .name("Golden Sunrise Light 2")
                            .description("A beautiful Golden Sunrise Light 2 frame.")
                            .price(280)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/golden_sunrise_light_02.png")
                            .info("golden_sunrise_light_02")
                            .build(),
                    Item.builder()
                            .name("Golden Sunrise Light 3")
                            .description("A beautiful Golden Sunrise Light 3 frame.")
                            .price(660)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/golden_sunrise_light_03.png")
                            .info("golden_sunrise_light_03")
                            .build(),
                    Item.builder()
                            .name("Golden Sunrise Light 4")
                            .description("A beautiful Golden Sunrise Light 4 frame.")
                            .price(1520)
                            .rarity(Rarity.EPIC)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/golden_sunrise_light_04.png")
                            .info("golden_sunrise_light_04")
                            .build(),
                    Item.builder()
                            .name("Golden Sunrise Light 5")
                            .description("A beautiful Golden Sunrise Light 5 frame.")
                            .price(3800)
                            .rarity(Rarity.LEGENDARY)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/golden_sunrise_light_05.png")
                            .info("golden_sunrise_light_05")
                            .build(),
                    Item.builder()
                            .name("Pastel Rainbow Dark 1")
                            .description("A beautiful Pastel Rainbow Dark 1 frame.")
                            .price(70)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/pastel_rainbow_dark_01.png")
                            .info("pastel_rainbow_dark_01")
                            .build(),
                    Item.builder()
                            .name("Pastel Rainbow Dark 2")
                            .description("A beautiful Pastel Rainbow Dark 2 frame.")
                            .price(240)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/pastel_rainbow_dark_02.png")
                            .info("pastel_rainbow_dark_02")
                            .build(),
                    Item.builder()
                            .name("Pastel Rainbow Dark 3")
                            .description("A beautiful Pastel Rainbow Dark 3 frame.")
                            .price(580)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/pastel_rainbow_dark_03.png")
                            .info("pastel_rainbow_dark_03")
                            .build(),
                    Item.builder()
                            .name("Pastel Rainbow Dark 4")
                            .description("A beautiful Pastel Rainbow Dark 4 frame.")
                            .price(1360)
                            .rarity(Rarity.EPIC)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/pastel_rainbow_dark_04.png")
                            .info("pastel_rainbow_dark_04")
                            .build(),
                    Item.builder()
                            .name("Pastel Rainbow Dark 5")
                            .description("A beautiful Pastel Rainbow Dark 5 frame.")
                            .price(3400)
                            .rarity(Rarity.LEGENDARY)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/pastel_rainbow_dark_05.png")
                            .info("pastel_rainbow_dark_05")
                            .build(),
                    Item.builder()
                            .name("Pastel Rainbow Light 1")
                            .description("A beautiful Pastel Rainbow Light 1 frame.")
                            .price(70)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/pastel_rainbow_light_01.png")
                            .info("pastel_rainbow_light_01")
                            .build(),
                    Item.builder()
                            .name("Pastel Rainbow Light 2")
                            .description("A beautiful Pastel Rainbow Light 2 frame.")
                            .price(240)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/pastel_rainbow_light_02.png")
                            .info("pastel_rainbow_light_02")
                            .build(),
                    Item.builder()
                            .name("Pastel Rainbow Light 3")
                            .description("A beautiful Pastel Rainbow Light 3 frame.")
                            .price(580)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/pastel_rainbow_light_03.png")
                            .info("pastel_rainbow_light_03")
                            .build(),
                    Item.builder()
                            .name("Pastel Rainbow Light 4")
                            .description("A beautiful Pastel Rainbow Light 4 frame.")
                            .price(1360)
                            .rarity(Rarity.EPIC)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/pastel_rainbow_light_04.png")
                            .info("pastel_rainbow_light_04")
                            .build(),
                    Item.builder()
                            .name("Pastel Rainbow Light 5")
                            .description("A beautiful Pastel Rainbow Light 5 frame.")
                            .price(3400)
                            .rarity(Rarity.LEGENDARY)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/pastel_rainbow_light_05.png")
                            .info("pastel_rainbow_light_05")
                            .build(),
                    Item.builder()
                            .name("Twilight Dark 1")
                            .description("A beautiful Twilight Dark 1 frame.")
                            .price(130)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/twilight_dark_01.png")
                            .info("twilight_dark_01")
                            .build(),
                    Item.builder()
                            .name("Twilight Dark 2")
                            .description("A beautiful Twilight Dark 2 frame.")
                            .price(360)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/twilight_dark_02.png")
                            .info("twilight_dark_02")
                            .build(),
                    Item.builder()
                            .name("Twilight Dark 3")
                            .description("A beautiful Twilight Dark 3 frame.")
                            .price(820)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/twilight_dark_03.png")
                            .info("twilight_dark_03")
                            .build(),
                    Item.builder()
                            .name("Twilight Light 1")
                            .description("A beautiful Twilight Light 1 frame.")
                            .price(130)
                            .rarity(Rarity.COMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/twilight_light_01.png")
                            .info("twilight_light_01")
                            .build(),
                    Item.builder()
                            .name("Twilight Light 2")
                            .description("A beautiful Twilight Light 2 frame.")
                            .price(360)
                            .rarity(Rarity.UNCOMMON)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/twilight_light_02.png")
                            .info("twilight_light_02")
                            .build(),
                    Item.builder()
                            .name("Twilight Light 3")
                            .description("A beautiful Twilight Light 3 frame.")
                            .price(820)
                            .rarity(Rarity.RARE)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/twilight_light_03.png")
                            .info("twilight_light_03")
                            .build(),
                    Item.builder()
                            .name("Twilight Light 4")
                            .description("A beautiful Twilight Light 4 frame.")
                            .price(1840)
                            .rarity(Rarity.EPIC)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/twilight_light_04.png")
                            .info("twilight_light_04")
                            .build(),
                    Item.builder()
                            .name("Twilight Light 5")
                            .description("A beautiful Twilight Light 5 frame.")
                            .price(4600)
                            .rarity(Rarity.LEGENDARY)
                            .type(ItemType.FRAME)
                            .version("2.0")
                            .image("/images/store/twilight_light_05.png")
                            .info("twilight_light_05")
                            .build()
            );

            itemRepository.saveAll(defaultItems);
            log.info("Successfully seeded {} items.", defaultItems.size());
        } else {
            log.info("Store already contains items. Skipping seeding.");
        }
    }
}
